Repository preactjs/preact, pull requests merged in 2020-04, with the labels that each got.

#2213 Skip setProperty for known bypass cases (key, children)
  src/diff/props.js
Labels: performance

#2386 implement strict-equality for vnodes
  compat/mangle.json
  compat/src/suspense.js
  compat/test/browser/suspense.test.js
  hooks/test/browser/useMemo.test.js
  mangle.json
  src/clone-element.js
  src/component.js
  src/create-element.js
  src/diff/children.js
  src/diff/index.js
  src/internal.d.ts
  test/browser/createContext.test.js
  test/browser/createElementProduction.test.js
  test/browser/lifecycles/componentDidCatch.test.js
  test/browser/lifecycles/getDerivedStateFromError.test.js
  test/browser/lifecycles/shouldComponentUpdate.test.js
Labels: enhancement, performance

#2461 Account for defaultProps when wrapping components with memo [fixes #2443]
  compat/src/index.d.ts
  compat/test/ts/memo.tsx
  src/index.d.ts
Labels: types

#2462 Tachometer benchmarks
  .gitignore
  benches/.gitignore
  benches/README.md
  benches/package.json
  benches/scripts/bench.js
  benches/scripts/config.js
  benches/scripts/index.js
  benches/scripts/paths.js
  benches/src/02_replace1k.html
  benches/src/keyed-children/index.js
  benches/src/keyed-children/store.js
  benches/src/text_update.html
  benches/src/util.js
Labels: performance

#2480 Add support for hooks inspection via devtools
  debug/src/debug.js
  hooks/mangle.json
  hooks/src/index.js
  hooks/test/browser/hooks.options.test.js
  src/internal.d.ts
Labels: devtools
