Repository preactjs/preact, pull requests merged in 2021-05, with the labels that each got.

#3143 Use Array.prototype.slice.call for children arguments
  src/clone-element.js
  src/create-element.js
  src/diff/index.js
  src/render.js
  src/util.js
Labels: performance

#3144 Improve typing of forwardRef
  compat/src/index.d.ts
Labels: types

#3166 [draft] Remove ie11 (additions)
  src/component.js
  src/diff/children.js
  src/diff/commit.js
  src/diff/component.js
  src/diff/unmount.js
Labels: Restructure
